"""create_auth_tables

Revision ID: c85ab03995de
Revises: cbc463a509d3
Create Date: 2026-05-29 19:50:05.308201+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c85ab03995de'
down_revision: Union[str, None] = 'cbc463a509d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Permission code (e.g., reimbursement:create)'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Human-readable permission name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed permission description'),
    sa.Column('resource', sa.String(length=50), nullable=False, comment='Resource part of the permission (e.g., reimbursement)'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action part of the permission (e.g., create, read, update, delete)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_index('ix_permissions_resource_action', 'permissions', ['resource', 'action'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Role name (e.g., admin, employee, approver, finance)'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='Human-readable role name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Role description and scope'),
    sa.Column('is_system_role', sa.Boolean(), server_default='false', nullable=False, comment='System roles cannot be modified or deleted'),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False, comment='Role priority for conflict resolution (higher = more authority)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('auth_events',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Event type: login_success, login_failure, logout, etc.'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='Client User-Agent header'),
    sa.Column('session_id', sa.String(length=36), nullable=True, comment='Session identifier'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional event details as JSON'),
    sa.Column('success', sa.Boolean(), server_default='true', nullable=False, comment='Whether the event was successful'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_events_created', 'auth_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_events_event_type'), 'auth_events', ['event_type'], unique=False)
    op.create_index('ix_auth_events_type', 'auth_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_auth_events_user_id'), 'auth_events', ['user_id'], unique=False)
    op.create_index('ix_auth_events_user_type', 'auth_events', ['user_id', 'event_type'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index('ix_auth_events_user_type', table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_user_id'), table_name='auth_events')
    op.drop_index('ix_auth_events_type', table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_event_type'), table_name='auth_events')
    op.drop_index('ix_auth_events_created', table_name='auth_events')
    op.drop_table('auth_events')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_permissions_resource_action', table_name='permissions')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
