"""initial_schema

Revision ID: cbc463a509d3
Revises: 
Create Date: 2026-05-29 14:47:01.665328+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc463a509d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key - UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft delete flag - true if record is deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('designations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key - UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft delete flag - true if record is deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('designation_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key - UUID v4'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID of the user who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft delete flag - true if record is deleted'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID of the user who soft-deleted this record'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('designations')
    op.drop_table('departments')
    # ### end Alembic commands ###
